### ISSUE TITLE
In Dev: GUI doesn't resize number of displayed rows based on number of results

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#102]
![image](https://user-images.githubusercontent.com/59544993/72856536-aaa1fa80-3c6f-11ea-8714-789820ae82c7.png)

**Comment by Jlance999** [comment]
I will work on this and have a solution in the morning.

**Comment by Jlance999** [comment]
Fixed, pull request added.

https://github.com/Ethck/Path-of-Accounting/pull/106

**Comment by Ethck** [comment]
Merged into dev.
