### ISSUE TITLE
In Dev: Mark of the Shaper fails

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#103]
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Failed to parse response from POE API. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Macro failed to lookup item from POE trade API. Here is the item in question.
====== ITEM DATA=====
Rarity: Unique
Mark of the Shaper
Opal Ring
--------
Requirements:
Level: 80
--------
Item Level: 86
--------
23% increased Elemental Damage (implicit)
--------
20% chance to Trigger Level 20 Summon Volatile Anomaly on Kill
Adds 13 to 55 Lightning Damage to Spells
9% increased maximum Energy Shield
6% increased maximum Life
63% increased Spell Damage if your other Ring is an Elder Item
Cannot be Stunned by Spells if your other Ring is a Shaper Item
--------
Let madness take control.
--------
Shaper Item

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================

**Comment by Ethck** [comment]
This is fixed now. The issue was that influenced items were being searched by the phrase "(influence) Item". Since MotS has "Shaper Item" and "Elder Item" it was being flagged as being influenced by both the Shaper and the Elder.
