### ISSUE TITLE
Removing x mod wildly mispriced.

### ISSUE THREAD

**Issue by gregorylivschitz** [Ethck/Path-of-Accounting#108]
Removing a mod from rares can cause really crazy mispricing. 

For instance this axe is about 5-8 ex, but the increased physical got removed showing up as 50 chaos:
[*] Found Rare item in clipboard: Plague Edge Siege Axe
[+] Found mod #% increased Physical Damage: 178
[+] Found mod Adds # to # Cold Damage (Local): 2
[+] Found mod #% increased Attack Speed (Local): 26
[+] Found mod #% to Global Critical Strike Multiplier: 25
[-] Removing the #% increased Physical Damage mod from the list due to no result
s found.
[$] Price: 1 x 48 chaos, 1 x 50 chaos

If you are not looking at the cmd, but only ingame this seems bad because it only shows 40 chaos.
What do you think we should do here?
Add it to the gui? Try to set a lower increased physical until we get a match? Doesn't poe macro use some machine learning algo api? Can we use that?
Do you accept pr's?

**Comment by Ethck** [comment]
I do accept PR's! Even better, if you want to chat I've got a discord set up here: https://discord.gg/BUV2x6N

Currently removing mods is not an ideal algorithm and just picks the last one on the list (except for a few pseudo mods that are given priority.)

**Comment by Ethck** [comment]
While not fixed, the merged PR does issue a warning about the volatility and discrepancy of items with fewer than 10 results. I will continue to monitor this and will eventually have a better pricing algorithm made.
