### ISSUE TITLE
Coding Guidelines

### ISSUE THREAD

**Issue by kevr** [Ethck/Path-of-Accounting#123]
We should come up with a set of coding guidelines, as I've seen some things mixed.

camelCase vs underline_thing, etc.

I saw some of the newer commits using camelCase, so I stuck with that, but I'm still unsure what's preferred by majority.

Depending on whatever you guys want, I can go through and refactor the style where it's needed.

Vote on naming conventions at the strawpoll posted in Discord #dev

```
# Decided project coding guidelines
Tab size: 4 spaces
Naming convention: PEP8 (CapitalClass and underscore_others)
https://www.python.org/dev/peps/pep-0008/#naming-conventions
```

**Comment by deathbeam** [comment]
Well at least Intellij really dislikes camel case and prefers snake_case, so I would say that is the way to go

**Comment by rhzk** [comment]
Well i prefer class names with all words Capital i.e ExampleClass,
function names with underscore: do_something()
and class members in camelCase: isRunning
so i guess my opinion is invalid xD

**Comment by deathbeam** [comment]
1. and 2. sounds correct, and 3rd should just follow 2. (that is what I think and also what IntelliJ thinks)

**Comment by kevr** [comment]
...vim + jedi master race

**Comment by kevr** [comment]
> Well i prefer class names with all words Capital i.e ExampleClass,
> function names with underscore: do_something()
> and class members in camelCase: isRunning
> so i guess my opinion is invalid xD

I'd say that one fits more with camelCase overall, even for function names

**Comment by kevr** [comment]
just to clarify, this would be about what the majority of our contributors prefer, not what IntelliJ or any other autocompletions suggest; autocomplete differs wildly from editor to editor, some with a configurable style.

**Comment by kevr** [comment]
Here's a way to simplify this thread: I've created a strawpoll that can be found in Discord; check OP.
