### ISSUE TITLE
Some Local Mods Not Handled Probably

### ISSUE THREAD

**Issue by Ethck** [Ethck/Path-of-Accounting#126]
Example Item:
Rarity: Unique
Loreweave
Elegant Ringmail
--------
Quality: +20% (augmented)
Armour: 452 (augmented)
Energy Shield: 158 (augmented)
--------
Requirements:
Level: 66
Str: 105
Dex: 87
Int: 105
--------
Sockets: G-G-R-B-R-R 
--------
Item Level: 8
--------
Has 6 Sockets
+22 to all Attributes
Adds 6 to 17 Physical Damage to Attacks
46% increased Global Critical Strike Chance
+45 to maximum Energy Shield
+23 to maximum Life
+22 to maximum Mana
26% increased Rarity of Items found
43% increased Elemental Damage
Your Maximum Resistances are 78%
--------
When it comes to finding a use for surplus,
a rich man has within himself
boundless creativity.

Currently, PoA translates the +45 to Maximum Energy Shield to `explicit.stat_3489782002`. Searching with this explicit stat does not yield any results (which should basically never happen with uniques). The correct translation is `explicit.stat_4052037485` which is actually +# to Maximum Energy Shield (Local).

**Comment by kevr** [comment]
This is being worked on in Df010's parse/lookup rewrite.
