### ISSUE TITLE
The Beachhead unique map lookup error.

### ISSUE THREAD

**Issue by Violet-Vibes** [Ethck/Path-of-Accounting#136]
```
> Rarity: Unique
> The Beachhead
> Harbinger Map
> --------
> Map Tier: 10
> Item Quantity: +41% (augmented)
> Item Rarity: +55% (augmented)
> --------
> Item Level: 75
> --------
> Area contains 6 extra Harbingers
> --------
>        
>     
> --------
> Travel to this Map by using it in a personal Map Device. Maps can only be used once.
> --------
> Corrupted
> 
```

**Comment by Ethck** [comment]
Greetings! I'm not sure what happens on your version, but the dev version (that is almost ready) does not have an issue with pricing it. Does the program crash upon looking this item up, or is it just the wrong price? Thanks for posting this issue!

**Comment by Violet-Vibes** [comment]
> Greetings! I'm not sure what happens on your version, but the dev version (that is almost ready) does not have an issue with pricing it. Does the program crash upon looking this item up, or is it just the wrong price? Thanks for posting this issue!

Hey! No, it just gives me that error, I do not use the GUI option, if that matters. Trying to price check it only gives me that error, no price, no crash :)

**Comment by Ethck** [comment]
Any chance you can post a screenshot?

**Comment by Violet-Vibes** [comment]
> Any chance you can post a screenshot?

https://i.imgur.com/2n1EwRA.png

**Comment by Ethck** [comment]
Okay, this issue has been fixed in the dev version (which anyone can use, but you have to have python installed...). I will mark it as fixed-in-dev. My hope is to have the 0.9 release out next week. 0.9 is a complete rewrite of the current version, so it's much faster and has much more utility than the 0.8 version and that's why it's taking so long to make the next version.

**Comment by Violet-Vibes** [comment]
> Okay, this issue has been fixed in the dev version (which anyone can use, but you have to have python installed...). I will mark it as fixed-in-dev. My hope is to have the 0.9 release out next week. 0.9 is a complete rewrite of the current version, so it's much faster and has much more utility than the 0.8 version and that's why it's taking so long to make the next version.

Oh, guess I missed that the dev branch was public, I'll take a look, thanks!

**Comment by Ethck** [comment]
For the dev branch you have to have python installed (and install the required libraries with `pip install -r requirements.txt`)

**Comment by Violet-Vibes** [comment]
> For the dev branch you have to have python installed (and install the required libraries with `pip install -r requirements.txt`)

I've done some python stuff in the past so it'll be alright, thanks! ;)

**Comment by Ethck** [comment]
No problem. Let me know if you have any other issues. Also, our Discord link is in the dev branch as well :) I will close this issue once master has fixed it (when I merge dev in...)
