### ISSUE TITLE
Failed to query item from trade API.

### ISSUE THREAD

**Issue by 1012-sp** [Ethck/Path-of-Accounting#139]
Macro failed to lookup item from POE trade API. Here is the item in question.
====== ITEM DATA=====
Rarity: Unique
Acton's Nightmare
Overgrown Shrine Map
--------
Map Tier: 13
Atlas Region: Valdo's Rest
Item Quantity: +85% (augmented)
Item Rarity: +226% (augmented)
--------
Item Level: 84
--------
Area has patches of burning ground
Area is inhabited by Skeletons
Restless Dead
Area is a large Maze
Area contains a Large Chest
--------
Curious, she shook it then,
And tiny screams emerged.
Curiouser, she shook again,
And an eerie silence purred.
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

================== END ISSUE DATA ==================

**Comment by Ethck** [comment]
Just to be sure, you are using the currently released version 0.8, correct? I'm trying to wrap up the 0.9 release (hopefully sometime this week) and it is drastically improved (and this error is not present in it!). Thank you for filing this issue.

**Comment by 1012-sp** [comment]
That is correct. Thank you for addressing it regardless. Looking forward to version 0.9
