### ISSUE TITLE
[Dev] Anointment's need special numbers to be searched

### ISSUE THREAD

**Issue by rhzk** [Ethck/Path-of-Accounting#150]
On items anointment's gives the name of the node it anoints but the trade website expects a number,
for example in game: 'Lava Lash' website: '30439'

We might have to manually look up all the anointment's on the website and make a conversion list

**Comment by Ethck** [comment]
![image](https://user-images.githubusercontent.com/44616794/74465616-986c4400-4e4a-11ea-9fbf-0a9cba085a78.png)
