### ISSUE TITLE
[Dev] There exists multiple versions of the exact same mod

### ISSUE THREAD

**Issue by rhzk** [Ethck/Path-of-Accounting#151]
For example 
explicit.stat_4070519133 #% Chance to Block Spell Damage while on Low Life
explicit.stat_2253286128 #% Chance to Block Spell Damage while on Low Life

**Comment by Ethck** [comment]
It's been a while since we've talked about this, but is it possible that one of those only appears on a certain unique?

Also, we can just change it to where it tries that, if it fails move to the next one.
