### ISSUE TITLE
Error when looking up value for elder shield

### ISSUE THREAD

**Issue by Flaxarn** [Ethck/Path-of-Accounting#159]
[![Screenshot from Gyazo](https://gyazo.com/25d2b0ba2d650852778cc6505f699596/raw)](https://gyazo.com/25d2b0ba2d650852778cc6505f699596)

[*] Found Rare item in clipboard: Havoc Bastion Ezomyte Tower Shield
[+] Found mod # to maximum Life (implicit): 40
[+] Found mod # to maximum Life: 64
[+] Found mod #% to all Elemental Resistances: 14
[+] Found mod # Life gained when you Block: 42
[+] Found mod Regenerate #% of Life per second: 1
[+] Found mod #% increased Armour (crafted): 18
[+] Found mod # to maximum Life (crafted): 16
[o] Combining the elemental resistance mods from the list into a pseudo-parameter
[+] Pseudo-mod +42% total Elemental Resistance (pseudo)
[o] Combining the maximum life mods from the list into a pseudo-parameter
[+] Pseudo-mod +120 to maximum Life (pseudo)
[-] Removing the # Life gained when you Block mod from the list due to no results found.
[-] Removing the Regenerate #% of Life per second mod from the list due to no results found.
[-] Removing the #% increased Armour mod from the list due to no results found.
[-] Removing the +# total maximum Life mod from the list due to no results found.
[!] Take any values after this with a grain of salt. You should probably do a MANUAL search
[-] Removing the +#% total Elemental Resistance mod from the list due to no results found.
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Something went horribly wrong. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Here is the item in question.
====== ITEM DATA=====
Rarity: Rare
Havoc Bastion
Ezomyte Tower Shield
--------
Quality: +25% (augmented)
Chance to Block: 24%
Armour: 746 (augmented)
--------
Requirements:
Level: 67
Str: 159
--------
Sockets: R-R-R
--------
Item Level: 85
--------
+40 to maximum Life (implicit)
--------
+64 to maximum Life
+14% to all Elemental Resistances
+42 Life gained when you Block
Regenerate 1% of Life per second
1% increased Damage per 1% Chance to Block Attack Damage
18% increased Armour (crafted)
+16 to maximum Life (crafted)
--------
Elder Item

====== TRACEBACK =====
Traceback (most recent call last):
  File "parse.py", line 886, in watch_clipboard
  File "parse.py", line 508, in query_trade
  File "parse.py", line 241, in fetch
  File "site-packages\requests\models.py", line 897, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================
Traceback (most recent call last):
  File "parse.py", line 886, in watch_clipboard
  File "parse.py", line 508, in query_trade
  File "parse.py", line 241, in fetch
  File "site-packages\requests\models.py", line 897, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Ethck** [comment]
I know this doesn't solve the issue right at the moment, but this bug has been fixed in the dev branch. I will be merging dev to master soon and issuing a new release.
