### ISSUE TITLE
Linux user question : Run Accounting.py

### ISSUE THREAD

**Issue by feydreva** [Ethck/Path-of-Accounting#163]
Hello, I am a Linux user.
I cloned and installed  following the instruction.

The only thing I am missing it Run Accounting.py

I tried ]$ python Accounting.py but that gave me errors.
What is the correct command to run it ?

Thank you

**Comment by rhzk** [comment]
Hi, could you post the errors you got? Thanks

**Comment by feydreva** [comment]
So i had some Tk error, which I solved
Now i get theses : 
```
`[feydreva@Spychea` Path-of-Accounting]$ python Accounting.py 
Traceback (most recent call last):
  File "Accounting.py", line 9, in <module>
    from item.generator import Currency, Weapon, parse_item_info
  File "/home/feydreva/Path-of-Accounting/item/generator.py", line 7, in <module>
    from item.itemModifier import ItemModifierType
  File "/home/feydreva/Path-of-Accounting/item/itemModifier.py", line 3, in <module>
    from attr import attrs
ImportError: cannot import name 'attrs' from 'attr' (/home/feydreva/.local/lib/python3.8/site-packages/attr.py)
`

**Comment by rhzk** [comment]
You need to install the libraries in requirements.txt
try to run "pip install -r requirements.txt"

**Comment by feydreva** [comment]
I did that 1st
Anyway, ran it again : 
>[feydreva@Spychea Path-of-Accounting]$ pip install -r requirements.txt
Ignoring pypiwin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: attr==0.3.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: attrs==19.3.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.4.3)
Requirement already satisfied: dataclasses==0.6 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (0.6)
Requirement already satisfied: idna==2.8 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.8)
Requirement already satisfied: keyboard==0.13.4 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (0.13.4)
Requirement already satisfied: Pillow==7.0.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (7.0.0)
Requirement already satisfied: pynput==1.6.6 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.6.6)
Requirement already satisfied: pyperclip==1.7.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (1.7.0)
Requirement already satisfied: requests==2.22.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (2.22.0)
Requirement already satisfied: requests-mock==1.7.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.7.0)
Requirement already satisfied: screeninfo==0.6.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (0.6.1)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.14.0)
Requirement already satisfied: tqdm==4.41.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (4.41.1)
Requirement already satisfied: typing==3.7.4.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (3.7.4.1)
Requirement already satisfied: urllib3==1.25.7 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (1.25.7)
Requirement already satisfied: timeago==1.0.13 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.0.13)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /home/feydreva/.local/lib/python3.8/site-packages (from pynput==1.6.6->-r requirements.txt (line 10)) (0.26)

**Comment by Ethck** [comment]
You have to use python3.7+. On most linux installs this requires you to use the `python3` command.

**Comment by feydreva** [comment]
>[feydreva@Spychea Path-of-Accounting]$ python3 Accounting.py 
Traceback (most recent call last):
  File "Accounting.py", line 9, in <module>
    from item.generator import Currency, Weapon, parse_item_info
  File "/home/feydreva/Path-of-Accounting/item/generator.py", line 7, in <module>
    from item.itemModifier import ItemModifierType
  File "/home/feydreva/Path-of-Accounting/item/itemModifier.py", line 3, in <module>
    from attr import attrs
ImportError: cannot import name 'attrs' from 'attr' (/home/feydreva/.local/lib/python3.8/site-packages/attr.py)

>[feydreva@Spychea Path-of-Accounting]$ python --version
Python 3.8.1

>[feydreva@Spychea Path-of-Accounting]$ python3 --version
Python 3.8.1

**Comment by rhzk** [comment]
Also you might want to try "python -m pip install -r requirements.txt"
or "python3 -m pip install -r requirements.txt"
to make sure it gets installed for the python version you are using, incase you have multiple versions installed

**Comment by Ethck** [comment]
You'll need to do `python3 -m pip install -r requirements.txt" like rhzk suggested. This will set up the libraries for python3, previously you've only set up python2.

**Comment by feydreva** [comment]
nop, it doesn't change anyhting....

> [feydreva@Spychea Path-of-Accounting]$ python3 -m pip install -r requirements.txt
Ignoring pypiwin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: attr==0.3.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: attrs==19.3.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.4.3)
Requirement already satisfied: dataclasses==0.6 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (0.6)
Requirement already satisfied: idna==2.8 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.8)
Requirement already satisfied: keyboard==0.13.4 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (0.13.4)
Requirement already satisfied: Pillow==7.0.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (7.0.0)
Requirement already satisfied: pynput==1.6.6 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.6.6)
Requirement already satisfied: pyperclip==1.7.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (1.7.0)
Requirement already satisfied: requests==2.22.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (2.22.0)
Requirement already satisfied: requests-mock==1.7.0 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.7.0)
Requirement already satisfied: screeninfo==0.6.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (0.6.1)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.14.0)
Requirement already satisfied: tqdm==4.41.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (4.41.1)
Requirement already satisfied: typing==3.7.4.1 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (3.7.4.1)
Requirement already satisfied: urllib3==1.25.7 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (1.25.7)
Requirement already satisfied: timeago==1.0.13 in /home/feydreva/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.0.13)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /home/feydreva/.local/lib/python3.8/site-packages (from pynput==1.6.6->-r requirements.txt (line 10)) (0.26)


>[feydreva@Spychea Path-of-Accounting]$ python3 Accounting.py 
Traceback (most recent call last):
  File "Accounting.py", line 9, in <module>
    from item.generator import Currency, Weapon, parse_item_info
  File "/home/feydreva/Path-of-Accounting/item/generator.py", line 7, in <module>
    from item.itemModifier import ItemModifierType
  File "/home/feydreva/Path-of-Accounting/item/itemModifier.py", line 3, in <module>
    from attr import attrs
ImportError: cannot import name 'attrs' from 'attr' (/home/feydreva/.local/lib/python3.8/site-packages/attr.py)


AS you see on previous post, I only have python 3.8.1 installed

**Comment by rhzk** [comment]
python --version does not necessary list all python installs, I have multiple installed and it only shows one.

I am not sure about linux, maybe Ethck can share some light but are you sure you dont have python installed in both /usr/lib/python3.8 and /home/feydreva/.local/lib/python3.8
Maybe thats whats causing the problem

**Comment by Ethck** [comment]
Do pip3 install attrs

**Comment by feydreva** [comment]
>[feydreva@Spychea Path-of-Accounting]$ pip3 install attrs
Requirement already satisfied: attrs in /usr/lib/python3.8/site-packages (19.3.0)

**Comment by rhzk** [comment]
maybe try copying the content of "/usr/lib/python3.8/site-packages" into "/home/feydreva/.local/lib/python3.8/site-packages"

Since pip seems to say its installed in /usr/ but when you are running it its looking in /home/

**Comment by Ethck** [comment]
Please join the discord: https://discordapp.com/invite/BUV2x6N

**Comment by Ethck** [comment]
That shouldn't be the problem rhzk.

**Comment by Ethck** [comment]
Try this: `sudo pip3 install -r requirements.txt`

**Comment by feydreva** [comment]
OK, got it to work using a virtual environment.
I will follow up tomorow

>[feydreva@Spychea Path-of-Accounting]$ pip install virtualenv --user
[feydreva@Spychea Path-of-Accounting]$ python3 -m venv env
[feydreva@Spychea Path-of-Accounting]$ source env/bin/activate
(env) [feydreva@Spychea Path-of-Accounting]$ pip install -r requirements.txt
(env) [feydreva@Spychea Path-of-Accounting]$ python Accounting.py

**Comment by Ethck** [comment]
Okay, it appears that there were some conflicts found between local & globally installed libraries... Not sure why though.
