### ISSUE TITLE
[Linux] F5 write :hideout instead of /hideout

### ISSUE THREAD

**Issue by feydreva** [Ethck/Path-of-Accounting#164]
F5 write :hideout instead of /hideout, spamming the global chat.

**Comment by rhzk** [comment]
Hi, is it possible for you to join the discord? https://discord.gg/6NqYg3

**Comment by rhzk** [comment]
After talking with feydreva we narrowed down the issue to pynput library, keyboard library works as expected. Running with sudo on linux resolves this issue temporarily

**Comment by Ethck** [comment]
Running with sudo just defaults to the keyboard library, but it's interesting that we have never found this before. I'll change the title to reflect that this is Linux only.
