### ISSUE TITLE
Getting failed to execute script phase

### ISSUE THREAD

**Issue by remusionut** [Ethck/Path-of-Accounting#168]
![image](https://user-images.githubusercontent.com/46572335/76656291-f5593800-6577-11ea-8456-b8baa7023126.png)

**Comment by rhzk** [comment]
Is this a old version?

**Comment by Ethck** [comment]
Please update. This is from a previous version.

**Comment by remusionut** [comment]
> Please update. This is from a previous version.

I don't think it is i downloaded the one from 2 hours ago

**Comment by rhzk** [comment]
are you missing settings.cfg file?

**Comment by remusionut** [comment]
> are you missing settings.cfg file?

no, it is there

**Comment by rhzk** [comment]
Did it ask you to update and you downloaded the "updated" version?
update is broken and downloads a old version atm
Ethck i tought you disabled that :(

**Comment by Ethck** [comment]
I did... But that was within the last 2 hours.

**Comment by remusionut** [comment]
still not working, this sucks. And no it did not ask me to update it, this is my first time using the program

**Comment by Ethck** [comment]
Please download the new version. I just put it up like 10 minutes ago.
https://github.com/Ethck/Path-of-Accounting/releases/tag/v0.9

**Comment by remusionut** [comment]
> Please download the new version. I just put it up like 10 minutes ago.
> https://github.com/Ethck/Path-of-Accounting/releases/tag/v0.9

just did it, working fine so far

**Comment by rhzk** [comment]
Nice :)

**Comment by Ethck** [comment]
In the mean time, join our Discord! I'm closing this issue now.
