### ISSUE TITLE
timeago.locales.en missing in EXE version

### ISSUE THREAD

**Issue by Ethck** [Ethck/Path-of-Accounting#172]
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Something went horribly wrong. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Here is the item in question.
====== ITEM DATA=====
Rarity: Rare
Kraken Dome
Golden Mask
--------
Evasion Rating: 96
Energy Shield: 19
--------
Requirements:
Level: 43
Dex: 44
Int: 96
--------
Sockets: G-B-B
--------
Item Level: 36
--------
+19 to Dexterity
+28 to maximum Life
11% increased Rarity of Items found
+14% to Cold Resistance

====== TRACEBACK =====
Traceback (most recent call last):
  File "site-packages\timeago\locales\__init__.py", line 25, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utils\common.py", line 159, in price_item
    priceInformation.create_at_cursor()
  File "gui\gui.py", line 146, in create_at_cursor
    self.add_components()
  File "gui\windows.py", line 133, in add_components
    time = timeago.format(now, date)
  File "site-packages\timeago\__init__.py", line 80, in format
  File "site-packages\timeago\locales\__init__.py", line 29, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================

**Comment by Mojar1** [comment]
Second this issue.
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Something went horribly wrong. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Here is the item in question.
====== ITEM DATA=====
Rarity: Rare
Dread Tether
Leather Belt
--------
Requirements:
Level: 24
--------
Item Level: 33
--------
+26 to maximum Life (implicit)
--------
+3 to maximum Energy Shield
+32 to maximum Life
Regenerate 1.1 Life per second
Reflects 6 Physical Damage to Melee Attackers
+27% to Fire Resistance (crafted)

====== TRACEBACK =====
Traceback (most recent call last):
  File "site-packages\timeago\locales\__init__.py", line 25, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utils\common.py", line 159, in price_item
    priceInformation.add_price_information(data, offline)
  File "gui\gui.py", line 146, in create_at_cursor
    self.add_components()
  File "gui\windows.py", line 133, in add_components
    time = timeago.format(now, date)
  File "site-packages\timeago\__init__.py", line 80, in format
  File "site-packages\timeago\locales\__init__.py", line 29, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================

**Comment by rhzk** [comment]
Until Ethck gets to update the release page I built a new exe version without this problem
that you can download here: https://www.dropbox.com/s/aibom8rn5oo01o6/Accounting.zip?dl=0

**Comment by rhzk** [comment]
Until Ethck gets to update the release page, I built a new .exe version that shouldn't have this problem that you can download here: https://www.dropbox.com/s/58f0hkjvlsx9utu/Accounting.zip?dl=0

**Comment by Ethck** [comment]
I'm testing fixes for this now, will update when it's fixed. For some reason, this bug is only present in the EXE version of PoA, so it's been difficult to handle.

**Comment by Ethck** [comment]
Fix here: https://github.com/Ethck/Path-of-Accounting/releases/tag/v0.91
