### ISSUE TITLE
Clipboard not working in Linux

### ISSUE THREAD

**Issue by InFerYes** [Ethck/Path-of-Accounting#183]
I have just installed the latest version of PoA and have it up and running, however it now sits idle at `[*] Watching clipboard (Ctrl+C to stop)...`

It does not catch items from the game with Ctrl+C. I have no output I can attach for debugging.

![PoA](https://i.imgur.com/f8mGlo5.png)

edit: you can see me using `python` and `python3`, but I have found they are the same

```
user@ranger ~ % python3 --version
Python 3.8.2
user@ranger ~ % python --version 
Python 3.8.2
```

**Comment by rhzk** [comment]
look in settings.cfg for hotkey combinations. We also have a discord you can join if you have questions or problems: https://discord.gg/fsz8zF

**Comment by InFerYes** [comment]
In settings all the hotkeys are `alt-`, was just confused since the old version used `ctrl-` and the competition also uses the CTRL key. On top of that it says"Watching clipboard", so naturally you copy things to the clipboard with `ctrl-c`

When I try with the default `alt-c` combination I'm getting more errors now, PoA crashes again:

```
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 
```

I have changed the combination to `ctrl-c` in settings, but the problem persists.

**Comment by rhzk** [comment]
From pyperclip site:

On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run “sudo apt-get install xclip” or “sudo apt-get install xsel” (Note: xsel does not always seem to work.)

Otherwise on Linux, you will need the gtk or PyQt4 modules installed.

try to install xclip with packman or something?

**Comment by InFerYes** [comment]
Thanks, that did the trick

```
sudo pacman -S xclip
resolving dependencies...
looking for conflicting packages...

Packages (1) xclip-0.13-2

Total Download Size:   0.01 MiB
Total Installed Size:  0.06 MiB
```

More things to add to the requirements/dependencies :+1:
