### ISSUE TITLE
Advanced Price checked bug

### ISSUE THREAD

**Issue by Sekhait** [Ethck/Path-of-Accounting#185]
While using the advanced price check, it would not stop popping up.
No matter what I did, it will just pop up after I said close and rendered the game unplayable.
Had to force the game to close

**Comment by rhzk** [comment]
Hi, is this on the release version?
Also could you post the item you where checking when this happened here (ctrl+c over the item to copy it then paste it here)?

If it bugs out again you can terminate python in taskmanager

**Comment by Sekhait** [comment]
Hi.

Sorry for the late reply.
Yes, on the release version.

**Comment by rhzk** [comment]
Is it still happening with the new version?
