### ISSUE TITLE
Opening with batch command

### ISSUE THREAD

**Issue by mithlug** [Ethck/Path-of-Accounting#187]
I'm using a batch file to start poe, firefox, pob at the same time. I wanted to add Accounting to that list. It currently opens up a start window but then I can't read what it prints before it closes. You can see my commands below. Any help or fix?

@echo off
cd C:\ [...] \My Games\Path of Exile\Accounting\
START "Accounting" "Accounting.exe"
exit

**Comment by Ethck** [comment]
If you remove the @echo off, what kind of error message do you get? Additionally, if you use the command prompt to run Accounting.exe, does any sort of error message pop up?

**Comment by mithlug** [comment]
Using command prompt starts the application but then closes before I can read. Removing echo or turning it to on doesn't keep the window open, neither does removing the exit command. I'm guessing it has to do with accounting running in a command window? Can you recreate it or run it from cmd-commands yourself?

**Comment by Ethck** [comment]
Hmm... I'm not super familiar with Batch scripting, but I can't even seem to get PoA to run with the start command. Try to see what happens if you `pause` instead of exit. Currently you are telling it to start and immediately exit.

**Comment by mithlug** [comment]
"If you wish to change the selected league you may do so in settings.cfg.
Valid league values are Delirium, Hardcore Delirium, Standard, Hardcore.
All values will be from the Hardcore league
[*] Loaded 402 bases and their prices."

And then the window closes. Also sometimes I'm getting an error that pathofexile.com is down. It seems to not be batch related but does accounting require poe to be started before it? And maybe the problem is that they start so close in time. Gonna try to have a long pause between the commands, I'll report back soon.

**Comment by mithlug** [comment]
"[!] Pathofexile.com seems to be down!
[!] Please restart the program when website is back up"

Is another error I'm getting sometimes. Even with an exceptionally long pause it still closes right after start. This time I commented out the commands to start accounting and just ran it manually after having poe running and logged on a char.

**Comment by mithlug** [comment]
"[!] Pathofexile.com seems to be down!
[!] Please restart the program when website is back up
[*] Loaded 13322 bases and their prices.
[*] Watching clipboard (Ctrl+C to stop)..."

Re un-zipped my files to C:\ [...] \Documents\Accounting instead of C:\ [...] \Documents\My Games\Path of Exile\Accounting and it seems to start properly and stays open. But weird that the site is down while it is actually up and running...

**Comment by Ethck** [comment]
The `pathofexile.com appears to be down` issue will be remedied in the next release. We put too strict of a timeout parameter on our request to make sure it was alive. PoA also does not require Path of Exile to be started.

**Comment by mithlug** [comment]
Might have been something with the space in "My Games" then on my end. Thanks for the quick replies and addressing the other stuff mentioned.

**Comment by rhzk** [comment]
2 seconds is pretty long timeout.. (2000 ms / ping)

if you open cmd and type "ping www.pathofexile.com" whats the maximum value you get?
