### ISSUE TITLE
Unable to find mod: 5% of Damage taken gained as Mana over 4 seconds when Hit

### ISSUE THREAD

**Issue by alexandruchirita4192** [Ethck/Path-of-Accounting#195]
The Path of Accounting Application with version 0.95 gives error "Unable to find mod: 5% of Damage taken gained as Mana over 4 seconds when Hit" for "Goathide Boots":

![image](https://user-images.githubusercontent.com/34884567/79056261-2010dc00-7c5d-11ea-9b80-b657b9e4a79e.png)

The error is non-blocking (application still can be used properly even if error occurs).

**Comment by Ethck** [comment]
Thank you for this report. This is viewed by PoE as `explicit.stat_472520716`. I will figure out why it is not being found, and will get a fix issued shortly.

**Comment by Ethck** [comment]
It is important to note that the inability to find this mod does not affect the pricing at all.
