### ISSUE TITLE
Unable to reallocate x bytes crash

### ISSUE THREAD

**Issue by piotrszymaniec** [Ethck/Path-of-Accounting#28]
as title says. Im sorry that i cant give more direct data about bug. Its just happens in random moments  while fetching prices.

**Comment by Ethck** [comment]
First question, Linux or Windows?
Second question, how often does it happen?

**Comment by Ethck** [comment]
Either way, this issue seems to come from how Path of Accounting interfaces with the clipboard... Going to look into this first thing.

**Comment by Ethck** [comment]
Ah, so the problem is not necessarily with the clipboard, but by the fact that there is an infinite loop that keeps going until your computer runs out of memory. I should be able to get a fix soon.

**Comment by Ethck** [comment]
I think this problem was solved with the linux fix. Trying out now.
