### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Ethck** [Ethck/Path-of-Accounting#30]
In game gui as opposed to a shell.

**Comment by zero-code-hero** [comment]
https://docs.python.org/3/library/tkinter.html is probably the fastest way to do this in python.

You could also look into something like electron.

**Comment by C1rdec** [comment]
@Ethck I can make something really fast. We just need a way to communicate to C#. I already have everything setup: Process discovery, KeyboardHandler, Window position, installer and a incoming trade manager.

I'm the father of [Poe Lurker](https://github.com/C1rdec/Poe-Lurker) we could team up for the love of POE.

**Comment by C1rdec** [comment]
I can redirect the standard output of your process and listen to everything you print in the shell.

**Comment by Ethck** [comment]
@C1rdec , that would be amazing! All for the community!

**Comment by Ethck** [comment]
Just let me know what I can do to help that process.

**Comment by C1rdec** [comment]
I'll start on that after work we just need to set a protocol

**Comment by Ethck** [comment]
What do you have in mind?

**Comment by C1rdec** [comment]
I just need a hook when you have the listed prices you could print a line that start with a combination of characters that I would recognize example `[PoeLurker] ...`

**Comment by C1rdec** [comment]
Lets connect on discord Cedrico#2163 I'll be on after work (in about 6h).

I'll make a simple implementation and I'll let you know what you could do to help me parse the information

**Comment by Ethck** [comment]
For Posterity, I'm Ethck#6879. I'm done with work about that time as well. I'll go ahead and send a friend invite. I've already made a branch you can fork (PoELurkerInt), it changed the pricing display to begin with "[PoELurker]" instead of [!].

**Comment by C1rdec** [comment]
pricing always start with [!] ? If yes that will do it

**Comment by Ethck** [comment]
Initially, but I also used that for error messages. So pricing starts with [PoELurker] in the PoELurkerInt branch.

**Comment by brynjolf** [comment]
Just for reference, I would still like a way to interact with the parsing through commandline, like now. I much prefer this over a tooltip since it works in all scenarios (with a dual monitor ofc)

**Comment by C1rdec** [comment]
This will be possible

**Comment by Ethck** [comment]
Yes, I too would like to use my second monitor for pricing and stuff (no reason to clutter my main screen lol). I will definitely keep the ability for the shell to be used (even on windows!).

**Comment by InFerYes** [comment]
@C1rdec will that be *NIX compatible?

**Comment by Ethck** [comment]
I will strive to keep a *NIX compatible version available with as many features as possible.

**Comment by C1rdec** [comment]
Here is the first draft of the UI.
Taking suggestions.

![Trade](https://user-images.githubusercontent.com/5436436/72101862-af6fc180-32f3-11ea-93fe-462fe57f7ada.gif)

**Comment by Heckner** [comment]
No results found should be a toucan png.

**Comment by C1rdec** [comment]
@Heckner 
![image](https://user-images.githubusercontent.com/5436436/72106441-5f95f800-32fd-11ea-8aca-3a41a9a8356b.png)

**Comment by woefulwabbit** [comment]
tkinter would be more platform agnostic than a C# based solution

**Comment by Ethck** [comment]
I've got a basic tkinter solution posted in dev. Will post a picture soon.

**Comment by Ethck** [comment]
[Gui](https://github.com/Ethck/Path-of-Accounting/blob/dev/images/sampleGui.png)

**Comment by Ethck** [comment]
![sampleGui](https://user-images.githubusercontent.com/44616794/72209266-663d8000-3461-11ea-8abf-7fa9284bb64b.png)

**Comment by Ethck** [comment]
@brynjolf with the latest settings commit, you can now disable the brand-new gui and maintain use of the shell version if you so wish.
