### ISSUE TITLE
Crash when price-checking Vaal Gems

### ISSUE THREAD

**Issue by CapCatatonic** [Ethck/Path-of-Accounting#31]
**Running on Linux via Wine** If a Vaal Skill Gem is put into clipboard, the application crashes and will not reopen until the Vaal Skill Gem is removed from clipboard. Not sure if Wine related.

Update: Seems to be crashing on all skill gems.

**Comment by Ethck** [comment]
I'm pretty sure this is not wine related, but thanks for including that! Currently all skill gems do not work.

**Comment by mlemily** [comment]
Can confirm not Wine, same issue on Windows.
