### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Xeverous** [Ethck/Path-of-Accounting#33]
An open source project should have a license. Otherwise it's not really possible to legally contribute.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

You have also commited some binary files into the repository (this is strongly discouraged in any project) - these files may be under own licenses, which complicates the problem. If you base the resulting application on these files, your final licence must satisfy their requirements.

I recommend to visit these:

- https://choosealicense.com/
- https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by Ethck** [comment]
Thanks! I'll look into this now!

**Comment by Ethck** [comment]
In addition, how should I distribute the binary files so people can get them? (FYI I use a Python library, pyinstaller, to generate all of those binary files.

**Comment by Ethck** [comment]
Okay, PyInstaller says "The executable bundles generated by PyInstaller from your source code can be shipped with whatever license you want."

**Comment by Ethck** [comment]
Fixed. Thanks for the notifications.

**Comment by Xeverous** [comment]
> how should I distribute the binary files so people can get them?

That's the thing. You should only **distribute them**. A project repository should only contain code that is absolutely necessary to build the project. Any files that are a result of the build, should be only present in releases (GitHub has a dedicated release page and [guide how to release binaries](https://help.github.com/en/github/administering-a-repository/creating-releases)).

Just don't treat the repository as "file hosting". It should only contain code and the related information. Anything else (including stuff necessary to run the final program) should be only present in release downloads.

If you use any third party code or binaries (which is always the case with Python since it does not compile natively and requires a standard library implementation) you need to comply with their license requirements. Its also good to list your dependencies (`requirements.txt` in the case of Python) so that everyone who follows given language's ecosystem can just fetch your code, fetch 3rd party code and build it using own toolchain (that is, possibly a different system/implementation than yours).
