### ISSUE TITLE
Normal Item Steel Ring does not work

### ISSUE THREAD

**Issue by KlumsyKyller** [Ethck/Path-of-Accounting#4]
Rarity: Normal
Steel Ring
--------
Requirements:
Level: 80
--------
Item Level: 78
--------
Adds 3 to 11 Physical Damage to Attacks (implicit)

**Comment by Ethck** [comment]
UPDATE: Items with implicit modifiers but no explicit modifiers fail.

**Comment by Ethck** [comment]
UPDATE: All items that are not Rare or UNIQUE fail. Refer to #11
