### ISSUE TITLE
Exception thrown when unidentified unique in clipboard

### ISSUE THREAD

**Issue by surculus12** [Ethck/Path-of-Accounting#42]
```
[*] Watching clipboard (Ctrl+C to stop)...
[*] Found Unique item in clipboard: Strapped Leather Strapped Leather
Traceback (most recent call last):
  File "parse.py", line 488, in <module>
  File "parse.py", line 417, in watch_clipboard
KeyError: 'corrupted'
[5600] Failed to execute script parse
```

Should read the rarity and base and infer the unique (or search base + unique?) if unidentified, or at least fail gracefully and/or display an error. It is probably confusing to some users since they can't restart the program until they clear their clipboard.

**Comment by Ethck** [comment]
Fixed in the dev branch now. Will release new version later today. Will re-evaluate exiting strategy.

**Comment by surculus12** [comment]
Awesome, thanks!
