### ISSUE TITLE
Parse.py is gone. Was using this file to run natively in Linux.

### ISSUE THREAD

**Issue by CapCatatonic** [Ethck/Path-of-Accounting#45]
I can still run parse.exe in Wine but would like to be able to run natively if possible. Even better would be having it put on a repository/PPA so it can be properly "installed" and update with all my other applications.

**Comment by Ethck** [comment]
My intention was to not have "releases" for *nix users and they could just clone the repo to get the bleeding edge version (what I would vastly prefer myself tbh). Would you rather see a linux version of releases?

**Comment by Ethck** [comment]
I will investigate using a PPA, not sure on the possibility of it though.

**Comment by CapCatatonic** [comment]
Overlooked the fact that the repo still had the .py file. That's my bad. Will use the clone method then. I'm not really sure what setting up a PPA entails but if it's a big project then I wouldn't worry about it, there's tons of better things to do.

**Comment by Ethck** [comment]
I'll work on it. Closing this for now.
