### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by epicwon** [Ethck/Path-of-Accounting#46]
Crashed while price checking 1 socket tombfist

Rarity: Unique
Tombfist
Steelscale Gauntlets
--------
Quality: +7% (augmented)
Armour: 70 (augmented)
Evasion Rating: 70 (augmented)
--------
Requirements:
Level: 36
Str: 29
Dex: 29
--------
Sockets: R-G G A 
--------
Item Level: 75
--------
Has 1 Abyssal Socket
4% increased maximum Life
With a Murderous Eye Jewel Socketed, Intimidate Enemies for 4 seconds on Hit with Attacks
With a Searching Eye Jewel Socketed, Maim Enemies for 4 seconds on Hit with Attacks
--------
"Ever watched a man crush another man's skull?
Hard to feel hope after that."

**Comment by epicwon** [comment]
Same with Darkness Enthroned, probably something to do with abyss sockets

**Comment by Ethck** [comment]
Just tried the search for the 1 socket tombfist. Dev branch does not crash, will push a new release in a couple of hours with a ton of fixes.

**Comment by epicwon** [comment]
Ok thx

**Comment by Ethck** [comment]
Darkness Enthroned also works fyi
