### ISSUE TITLE
Remnant of Corruption ain't 100c

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#48]
Rarity: Currency
Remnant of Corruption
--------
Stack Size: 9/9
--------
Corrupts the Essences trapping a monster, modifying them unpredictably
--------
Right click this item then left click a monster trapped by Essences to corrupt them. Corrupted Essences cannot be modified again.
Shift click to unstack.
--------
Note: ~price 1 alch

**Comment by Ethck** [comment]
Fixed in dev.
