### ISSUE TITLE
Doesn't support checking items in chat.

### ISSUE THREAD

**Issue by SyncStelar** [Ethck/Path-of-Accounting#49]
[*] Found Unique item in clipboard: <<set:MS>><<set:M>><<set:S>>Atziri's Foible Paua Amulet                             [!] Something went horribly wrong. Please make an issue on the github page and include the item that caused this error. https://github.com/ethck/path-of-accounting/issues                                                                      [!] No results!

**Comment by Heckner** [comment]
Specifically unique items, the "<set:MS><set:M><set:S>" string removes the unique identifier.

**Comment by Ethck** [comment]
Fixed in Dev.
