### ISSUE TITLE
Magic Abyss Jewel dnw

### ISSUE THREAD

**Issue by KlumsyKyller** [Ethck/Path-of-Accounting#5]
Rarity: Magic
Fuelling Ghastly Eye Jewel of Extinguishing
--------
Abyss
--------
Item Level: 56
--------
6% chance to Avoid being Ignited
Minions Regenerate 3 Life per second
--------
Place into an Abyssal Socket on an Item or into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

**Comment by KlumsyKyller** [comment]
Unique Jewel also not working

Rarity: Unique
Inertia
Crimson Jewel
--------
Radius: Large
--------
Item Level: 78
--------
+23 to Strength
Dexterity from Passives in Radius is Transformed to Strength
--------
There is no force without movement.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

**Comment by KlumsyKyller** [comment]
No unique jewels work, appears that only rare jewels work

**Comment by Ethck** [comment]
Unique jewel, refer to #3 
Magic jewel, refer #11
