### ISSUE TITLE
Un-ided maps crash

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#50]
Rarity: Magic
Bone Crypt Map
--------
Map Tier: 4
--------
Item Level: 71
--------
Unidentified
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
//

Rarity: Unique
Cemetery Map
--------
Map Tier: 3
--------
Item Level: 69
--------
Unidentified
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
//

**Comment by Ethck** [comment]
The first map works, but the second one does not. Will issue a fix soon.

**Comment by Ethck** [comment]
Fixed in dev
