### ISSUE TITLE
Blight maps crash

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#51]
Rarity: Normal
Blighted Precinct Map
--------
Map Tier: 7
--------
Item Level: 75
--------
Area is infested with Fungal Growths (implicit)
Natural inhabitants of this area have been removed (implicit)
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
//

**Comment by Ethck** [comment]
Fixed in dev. Will release later.
