### ISSUE TITLE
Pseudo mods dont get combined properly

### ISSUE THREAD

**Issue by Gladaed** [Ethck/Path-of-Accounting#52]
X increased damage has a pseudo mod. The tool does not appear to combine them.

example:

> Rarity: Rare
> Mind Gyre
> Opal Ring
> --------
> Quality (Elemental Damage): +20% (augmented)
> --------
> Requirements:
> Level: 80
> --------
> Item Level: 84
> --------
> 30% increased Elemental Damage (implicit)
> --------
> 24% increased Fire Damage
> Adds 14 to 28 Fire Damage to Attacks
> +62 to maximum Life
> +32 to maximum Mana
> +44% to Lightning Resistance
> Curse Enemies with Level 8 Flammability on Hit
> --------
> Warlord Item

produces

> [*] Found Rare item in clipboard: Mind Gyre Opal Ring
> [+] Found mod +30% increased Elemental Damage (implicit)
> [+] Found mod +24% increased Fire Damage
> [+] Found mod +14dds # to # Fire Damage to Attacks
> [+] Found mod +62 to maximum Life
> [+] Found mod +32 to maximum Mana
> [+] Found mod +44% to Lightning Resistance
> [+] Found mod +8urse Enemies with Level # Flammability on Hit
> [o] Combining the elemental resistance mods from the list into a pseudo-parameter
> [+] Pseudo-mod +44% total Elemental Resistance (pseudo)
> [o] Combining the maximum life mods from the list into a pseudo-parameter
> [+] Pseudo-mod +62 to maximum Life (pseudo)
> [-] Removing the #% increased Elemental Damage mod from the list due to no results found.
> [-] Removing the #% increased Fire Damage mod from the list due to no results found.
> [-] Removing the Adds # to # Fire Damage to Attacks mod from the list due to no results found.
> [-] Removing the # to maximum Mana mod from the list due to no results found.
> [-] Removing the Curse Enemies with Level # Flammability on Hit mod from the list due to no results found.
> [!] Take any values after this with a grain of salt. You should probably do a MANUAL search
> [-] Removing the +# total maximum Life mod from the list due to no results found.
> [!] Take any values after this with a grain of salt. You should probably do a MANUAL search
> [$] Lowest 10 prices: 1 x 85 chaos, 1 x 100 chaos, 2 x 1 exa, 1 x 1.5 exa, 3 x 2 exa, 1 x 3 exa, 1 x 3.5 exa

It also cut the flat fire too early.
Parsing of fire damage was bugged in the output. Same for various other mods.

It would be great if you could get your tool added to PAL https://github.com/POE-Addon-Launcher/PAL2 that one appears abandoned though and could use a fork.

**Comment by Ethck** [comment]
The parsing error has been fixed. I am contemplating a method in which to assign priority to different mods easily, but it is a lot of work. Given the mods on this ring, what would you say is the priority of each stat? I am imagining something like the following:
1. Curse enemies...
2. Max life
3. Resists
4. Increased Fire
5. Flat fire
6. Max mana

**Comment by Gladaed** [comment]
I am not sure about the curse mod. I think lvl 5 is about equivalent. I am unsure about your algorithm.

The ring is a Flammability CoH ring with a single high tier res, a slightly better than crafted life mod with the option of divining and a couple of fire mods.

priority is:

CoH Flammability level X
(pseudo) open prefix OR life roll >40 
Fire Damage > 50
High % non fire specific Resist
High % specific Resist
Pseudo Resist
Flat Fire
Mana

If you want we can go over a couple of items/talk in discord. This is not the best format I think.

**Comment by Ethck** [comment]
Yeah, discord can get a lot more done. The troublesome part about this is trying to make rules that will work with virtually every item. Feel free to add me and we can chat. Ethck#6879
