### ISSUE TITLE
Unique Item causes error: Crown of the Inward Eye

### ISSUE THREAD

**Issue by DreamzorRedux** [Ethck/Path-of-Accounting#53]
EDIT: I forgot to mention that the item was copied from chat. I just noticed that a this was highlighted in issue #49 

Here is the message in console:

```
[*] Found Unique item in clipboard: <<set:MS>><<set:M>><<set:S>>Crown of the Inward Eye Prophet Crown
[-] Only showing results that are: 2 linked
[!] Something went horribly wrong. Please make an issue on the github page and include the item that caused this error. https://github.com/ethck/path-of-accounting/issues
[!] No results!
```

**Comment by Ethck** [comment]
Thanks for the edit. It is indeed related to #49. For some reason GGG adds `<<set:MS>><<set:M>><<set:S>>` or something similar in front of unique items displayed in chat... I'll trim and have a hotfix out later.
