### ISSUE TITLE
minions turns into inions?

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#54]
> Rarity: Rare
Grim Vision
Ghastly Eye Jewel
--------
Abyss
--------
Requirements:
Level: 33
--------
Item Level: 77
--------
+26 to maximum Life
Minions deal 5 to 7 additional Chaos Damage
Minions have +143 to Accuracy Rating
Minions have 4% chance to Blind on Hit with Attacks
--------
Place into an Abyssal Socket on an Item or into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

![image](https://user-images.githubusercontent.com/59544993/72180869-f36ad100-339c-11ea-852c-b4f80def074d.png)

Also... It made a pseudo for one mod, does it use that pseudo in addition or as a replacement to the original?

**Comment by Ethck** [comment]
Fixed in dev. Pseudo mods replace the mod(s) that they combine during the search request.
