### ISSUE TITLE
Un-modded maps crash

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#55]
Normal, rare, it doesn't like sans mods

> Rarity: Normal
>Shore Map
>--------
>Map Tier: 7
>--------
>Item Level: 77
>--------
>Travel to this Map by using it in a personal Map Device. Maps can only be used once.

> Rarity: Normal
>Armoury Map
>--------
>Map Tier: 5
>--------
>Item Level: 73
>--------
>Travel to this Map by using it in a personal Map Device. Maps can only be used once.

**Comment by Ethck** [comment]
Thank you @UniQueKakarot for the help! This issue was already solved in a previous commit to dev. I just haven't been able to push to live yet because I'm working on a GUI.

**Comment by Ethck** [comment]
The issue was the lack of iiq on normal maps. This error was the same as the one for blighted maps, and was thus fixed with the blighted map fix.
