### ISSUE TITLE
Prophecies returning wrong prices

### ISSUE THREAD

**Issue by woefulwabbit** [Ethck/Path-of-Accounting#57]
All prophecies are returning 
[$] Lowest 6 prices: 2 x 1 jew, 2 x 1 chrom, 2 x 1 alt

Which is obviously wrong for something like:
[*] Found Normal item in clipboard: The Jeweller's Touch 
[$] Lowest 6 prices: 2 x 1 jew, 3 x 1 chrom, 1 x 1 alt

**Comment by zero-code-hero** [comment]
Currently they are not being searched at all.

**Comment by Ethck** [comment]
Fixed in latest dev commit. Will release a new version after testing is done.
