### ISSUE TITLE
Suggestion: Use cached poe.ninja api db for instant pricing

### ISSUE THREAD

**Issue by woefulwabbit** [Ethck/Path-of-Accounting#58]
poe.ninja has an api:
https://www.reddit.com/r/pathofexiledev/comments/d9ubuv/poeninja_api/

If you cache data from there, you can show prices instantly for a large proportion of searches

**Comment by Ethck** [comment]
I'll look into it. Currently PoA does no such caching, but you're definitely right. This would provide faster speeds.

**Comment by Ethck** [comment]
Okay, so I've set up the new base pricing to use ninja's API. I might also move currency items over, but that requires a bit of a rewrite to that section of the codebase.
