### ISSUE TITLE
Broke with

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#6]
Rarity: Unique
Kaom's Roots
Titan Greaves
--------
Quality: +28% (augmented)
Armour: 308 (augmented)
--------
Requirements:
Level: 68
Str: 120
--------
Item Level: 72
--------
Adds 45 to 68 Fire Damage if you've Killed Recently
--------
Has no Sockets
Cannot be Knocked Back
+158 to maximum Life
Action Speed cannot be modified to below base value
Unwavering Stance
--------
Don't flinch. It's a waste of good hitting time.
//
Rarity: Magic
Bubbling Divine Life Flask of Heat
--------
Recovers 1200 (augmented) Life over 3.00 (augmented) Seconds
Consumes 15 of 45 Charges on use
Currently has 0 Charges
--------
Requirements:
Level: 60
--------
Item Level: 60
--------
50% reduced Amount Recovered
135% increased Recovery rate
50% of Recovery applied Instantly
Immunity to Freeze and Chill during Flask effect
Removes Freeze and Chill on use
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.
//
Rarity: Gem
Bloodlust Support
--------
Attack, Physical, Support, Melee
Level: 1
Mana Multiplier: 125%
Quality: +10% (augmented)
Experience: 1/69,833
--------
Requirements:
Level: 18
Str: 33
--------
Supports melee attack skills, causing them to deal more damage against bleeding enemies, but preventing those skills from inflicting bleeding on enemies in any way.
--------
Supported Skills deal 40% more Melee Physical Damage against Bleeding enemies
Supported Attacks cannot cause Bleeding
Supported Skills deal 5% increased Melee Damage against Bleeding Enemies
--------
This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Active Skill Gem you wish to augment. Right click to remove from a socket.
--------
Corrupted
//
Rarity: Rare
Dream Scum
Leyline Map
--------
Map Tier: 6
Item Quantity: +58% (augmented)
Item Rarity: +34% (augmented)
Monster Pack Size: +22% (augmented)
--------
Item Level: 73
--------
Players are Cursed with Enfeeble
Monsters fire 2 additional Projectiles
Monsters deal 79% extra Damage as Cold
All Monster Damage from Hits always Ignites
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
//
Rarity: Rare
Sol Locket
Black Maw Talisman
--------
Requirements:
Level: 70
Dex: 155
--------
Sockets: G 
--------
Item Level: 80
--------
Talisman Tier: 1
--------
Has 1 Socket (implicit)
--------
23% increased Global Critical Strike Chance
+34% to Global Critical Strike Multiplier
21% increased Evasion Rating
+88 to maximum Life
+16 to maximum Mana
+38% to Cold Resistance
--------
The First Ones stalk with us
upon this lifelong hunt,
and cast their contempt
upon those that would make us their prey.
- The Wolven King
--------
Corrupted
//
Rarity: Normal
Polished Cartography Scarab
--------
35% more Maps found in Area
--------
For your loyalty and valour, honoured Betucia, we are proud to put
the requisition of dream-artefacts in your capable hands.
--------
Can be used in a personal Map Device to add modifiers to a Map.
//

**Comment by Heckner** [comment]
forget the belt, nevermind the belt

**Comment by Ethck** [comment]
Kaom's Roots refer to #3 
Scarabs refer to #12 
Gems refer to #13 
Flasks refer to #15 
Maps refer to #19
