### ISSUE TITLE
Influenced boots not returning prices

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#60]
> Rarity: Rare
>Ghoul Hoof
>Wyrmscale Boots
>--------
>Armour: 92
>Evasion Rating: 92
>--------
>Requirements:
>Level: 63
>Str: 48
>Dex: 48
>--------
>Sockets: R-R-R 
>--------
>Item Level: 79
>--------
>+56 to maximum Life
>14% increased Rarity of Items found
>27% increased Stun and Block Recovery
>8% chance to avoid Projectiles
>--------
>Crusader Item
![image](https://user-images.githubusercontent.com/59544993/72208916-8ff4a800-345d-11ea-9add-108d4dab26e7.png)

**Comment by Ethck** [comment]
Fixed in dev.
