### ISSUE TITLE
[RuntimeError] maximum recursion depth exceeded when running "poetry install"

### ISSUE THREAD

**Issue by CapCatatonic** [Ethck/Path-of-Accounting#64]
Using Python 3.7.5 on Linux Mint.

**Comment by Ethck** [comment]
I've also seen this issue a couple of times, but It does not seem to stop everything from working on my end. If you try running PoA, what happens?

**Comment by Ethck** [comment]
Also, try doing `poetry install -vvv`

**Comment by CapCatatonic** [comment]
The output from trying with python, python3 and python3.7

`capcatatonic@thehelm:~/Desktop/Path-of-Accounting$ python parse.py
  File "parse.py", line 216
    url = f'https://www.pathofexile.com/api/trade/fetch/{",".join(q_res["result"][i:i+10])}?query={q_res["id"]}'
                                                                                                               ^
SyntaxError: invalid syntax
`


`capcatatonic@thehelm:~/Desktop/Path-of-Accounting$ python3 parse.py
Traceback (most recent call last):
  File "parse.py", line 3, in <module>
    from tkinter import Tk, TclError
ModuleNotFoundError: No module named 'tkinter'
`


`capcatatonic@thehelm:~/Desktop/Path-of-Accounting$ python3.7 parse.py
Traceback (most recent call last):
  File "parse.py", line 3, in <module>
    from tkinter import Tk, TclError
ModuleNotFoundError: No module named 'tkinter'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
`
`Original exception was:
Traceback (most recent call last):
  File "parse.py", line 3, in <module>
    from tkinter import Tk, TclError
ModuleNotFoundError: No module named 'tkinter'
`

Using the -vvv switch doesn't seem to change anything

**Comment by Ethck** [comment]
Hmmm.... This appears to be an issue with poetry installing tkinter wrong. I'll investigate. In the mean time, just install the libraries that are missing. (I swear I won't be adding many more...)

**Comment by zero-code-hero** [comment]
Don't try to run this with anything less than python 3.7, it simply won't work.

Make sure that the pip install that you're using to install poetry is correctly tied to your python 3.7.

One of these commands should work, if they don't then you need to fix your pip install.
```
python3.7 -m pip
python3.7 -m pip3 
```

You can also check with the which command:
```
C:\Users\name\Documents\Path-of-Accounting>which pip
/c/Users/name/AppData/Local/Programs/Python/Python37/Scripts/pip
```

Then 
```
pip install poetry
poetry install
```

Finally 
```
poetry shell
python parse.py
```

**Comment by Ethck** [comment]
I cannot seem to get poetry to work either. For now, here is the list of required libraries you will need to have in order to run:
* requests
* pillow
* keyboard (if you want shortcuts)
* colorama
* typing

Maybe in the future, @LPiner can get poetry to work, but it seems to break on pillow...
