### ISSUE TITLE
Multistrike Support error

### ISSUE THREAD

**Issue by tatyrll** [Ethck/Path-of-Accounting#67]
[*] Found Gem item in clipboard: Multistrike Support Vaal Multistrike Support
[!] Something went horribly wrong. Please make an issue on the github page and include the item that caused this error. https://github.com/ethck/path-of-accounting/issues

**Comment by Ethck** [comment]
This issue was caused by the Multistrike Support containing the phrase "Cannot support Vaal skills". The previous implementation of testing for Vaal skills was simply searching if "Vaal" was anywhere in the gem description. This has been remedied.
