### ISSUE TITLE
Crash on non UTF-8 characters being in the Clipboard

### ISSUE THREAD

**Issue by eroglu94** [Ethck/Path-of-Accounting#68]
Hi, exe crashes after double clicking the exe. Gives really quick message and quits the console. i was able to catch the message (See image). It tries to load something(i guess) for 3-4 seconds at the begining, if you press ctrl+c in that time, program loads correctly, otherwise it crashes

![Screenshot_2](https://user-images.githubusercontent.com/11258914/72220645-d2081180-3563-11ea-84ca-0ebf8610da9e.png)

**Comment by kevinrobbins** [comment]
If you haven't already, try to put something else on your clipboard. I've noticed that if anything is on the clipboard that will crash the program, it will crash every time you start the program until you copy something safe. No guarantees that is the issue though.

**Comment by Ethck** [comment]
According to your error message, something in your clipboard (that PoA reads) is not compatible with the UTF-8 codec. This is likely a character with an accent mark or possibly even in another language. I'll see if I can replicate the error and/or create some sort of fix for it.
