### ISSUE TITLE
Suggestion: Instead of crash -> give error message

### ISSUE THREAD

**Issue by eroglu94** [Ethck/Path-of-Accounting#69]
Instead of crash message, program should be able to give error message. It is hard to restart again and again. Wrapping all the main part in try-catch block maybe?

**Comment by zero-code-hero** [comment]
Fix in https://github.com/Ethck/Path-of-Accounting/pull/72

Fix will give better instructions on how to open an issue, what to add, and will not cause a hard restart to be required.

**Comment by Ethck** [comment]
Thanks for the great work @LPiner. I will review the code later, and most likely merge it.
