### ISSUE TITLE
GUI is not descriptive

### ISSUE THREAD

**Issue by eroglu94** [Ethck/Path-of-Accounting#70]
GUI is not descriptive, item price is 5C, 20C, 70C, 1EX. But it shows Exalted image with wrongly placed prices.

![Screenshot_4](https://user-images.githubusercontent.com/11258914/72220811-bbfb5080-3565-11ea-95a5-ed2e6a9f60d7.png)

**Comment by Ethck** [comment]
I have noticed this issue as well. I am working to remedy it in a later patch. Currently the code does not understand that 1ex > 1c, so I'm going to fix that as well.

**Comment by Ethck** [comment]
In addition, what kind of details would you want to see on the simple search feature? The planned advanced search feature will by default include a lot of information.

**Comment by eroglu94** [comment]
The current console message is fine atm. UI can show that. 1x5C , 1x20C, etc. But listed time is important in some cases. For example, the item price showed 1x10C, 10x20C. You may think that item price bigger or equal then 10C, but maybe he listed the item 1 week ago and there was no buyer to that. So the item price should be lower than 10C. 

Btw, for item prices, you can do poe.ninja check, and store the prices in program memory to quick currency comparison check. 

I wish i could help you with the code but I have limited knowledge about py. I am trying to help you with my comments.

**Comment by Jlance999** [comment]
Just wanted to update on this. I have made a ton of updates to the GUI, they are not yet merged but you can view examples and give further suggestions in the discord at https://discord.gg/mfKT7E.

**Comment by Ethck** [comment]
Updates to the gui have indeed been made. It is much more descriptive than its predecessor. I will work on incorporating the poe.ninja check soon.
