### ISSUE TITLE
Black and ISort Codebase

### ISSUE THREAD

**Issue by zero-code-hero** [Ethck/Path-of-Accounting#73]
For readability this codebase should be [Blacked ](https://black.readthedocs.io/en/stable/index.html) and [ISorted](https://pypi.org/project/isort/).

This should also be hooked up to pre-commit hooks.

I am willing to do this but it's going reformat a large portion of the codebase.

**Comment by Ethck** [comment]
I can do it. I really do need to work on reformatting it... It is becoming quite a clutter recently.

**Comment by zero-code-hero** [comment]
These tools will help with the styling of the code but any actual refactoring you will have to do. I'll go ahead and build the config files for you.

**Comment by zero-code-hero** [comment]
@Ethck how do you feel about 120 line length instead of the standard 88?
