### ISSUE TITLE
SetForegroundWindow() crash

### ISSUE THREAD

**Issue by kevr** [Ethck/Path-of-Accounting#74]
Ran `ctrl+c` over a `Seething Divine Flask of Staunching`, the executable just crashes with no error information.

**Comment by kevr** [comment]
This isn't reproducible by me every time... I'm not sure it was 100% related to the flask, perhaps something else in the process.

**Comment by zero-code-hero** [comment]
Can you paste the entire item to here please. Will make it easier to debug.

**Comment by kevr** [comment]
Unfortunately I've found this to happen on many items. It seems to crash after I use it one or two times.

Edit: is there a log file that's created I could provide?

**Comment by Ethck** [comment]
Currently there is no logging system in place unless you run the executable through the command prompt. I will eventually remedy this. While refactoring the code, it appears that something broke. I will get this issue fixed soon.

**Comment by Ethck** [comment]
So the error appears to be the following:
```
Traceback (most recent call last):
  File "parse.py", line 888, in <module>
    watch_clipboard(league)
  File "parse.py", line 848, in watch_clipboard
    testGui.assemble_price_gui(price, currency)
  File "C:\Users\User\Downloads\Path-of-Accounting\testGui.py", line 21, in assemble_price_gui
    win32gui.SetForegroundWindow(root.winfo_id())
pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')
```
I am investigating the cause of this issue. It does not seem to be related to any of the items held within the clipboard at any given time.

**Comment by Ethck** [comment]
I have found the solution! Will be pushing to dev and you can expect a new release tomorrow(Monday).

**Comment by kevr** [comment]
Nice! That was quick. Thanks, Ethck
