### ISSUE TITLE
Poetry [MaxRecursionDepth] while installing

### ISSUE THREAD

**Issue by zero-code-hero** [Ethck/Path-of-Accounting#75]
Workaround for now is to blow away your venv and reinstall from scratch.

Will look into a permanent fix.

**Comment by woefulwabbit** [comment]
This is what I'm trying to do, not sire if I'm doing anything wrong

```
sudo apt install python3.7
virtualenv -p python3.7 venv
source venv/bin/activate
pip install poetry
python -m poetry install
```

This is what I get:
```
Installing dependencies from lock file

[RecursionError]
maximum recursion depth exceeded
```

Do we really need poetry or could we go back to requirements.txt?

**Comment by zero-code-hero** [comment]
Don't install poetry inside of the venv, it needs to be outside so its dependencies don't interfere with the project. 

You also don't need to create the venv, poetry will take care of that for you with poetry install.

https://python-poetry.org/docs/

**Comment by zero-code-hero** [comment]
Suspected bug in poetry https://github.com/python-poetry/poetry/issues/1238

**Comment by zero-code-hero** [comment]
@woefulwabbit the next time you install try deleting the .lock file and running install.
