### ISSUE TITLE
Magic 5-link Chest dnw

### ISSUE THREAD

**Issue by KlumsyKyller** [Ethck/Path-of-Accounting#8]
Rarity: Magic
Rotund Sun Plate of the Lizard
--------
Armour: 451
--------
Requirements:
Level: 45
Str: 124
--------
Sockets: G-G-R-R-R 
--------
Item Level: 61
--------
+64 to maximum Life
Regenerate 2.5 Life per second

**Comment by Ethck** [comment]
Refer to #11
