### ISSUE TITLE
Advanced Item Lookup

### ISSUE THREAD

**Issue by Ethck** [Ethck/Path-of-Accounting#84]
The advanced item description window must contain the following features:
* Time posted
* All mods with a toggle button to include them or not
* A button to disable all mods (search just for base, influence, corrupted status, ilvl, links)
* Option to ignore base
* More? Taking suggestions.

**Comment by WilJames** [comment]
Hi, add search for color sockets, enchant.

**Comment by Ethck** [comment]
Socket colors is doable, for enchants are you just wanting it to toggle whether or not to use the enchant in the search?

**Comment by Ethck** [comment]
Simple Advanced search is added thanks to rhzk in #160. Adding in more features now.

**Comment by Ethck** [comment]
Completed as of today (at least a simple version.) More settings coming later.
