### ISSUE TITLE
Error: Some Items Vastly Mispriced

### ISSUE THREAD

**Issue by kevr** [Ethck/Path-of-Accounting#86]
There are gems, jewels, and a few other types of items that are seriously mispriced by this thing. Talking about a 10c jewel is worth 3 ex, something else worth basically nothing worth 30 ex... something is wrong with the pricing mechanism here.

The old poe.trade macro did not price this badly. Not really sure what's going on, but figure I'd let you guys know.

**Comment by Ethck** [comment]
Do you have any examples of these vastly mispriced items? The current search algorithm implements the following restrictions:
* Ignore less than 5 links
* Keep corruption status
* Keep pseudo-life, pseudo-resists
* Keep gem level, gem quality
* Keep base (this is likely the culprit for most vastly mispriced items).

The search algorithm will be modified in a later update, but I'm working on some other updates atm.

**Comment by kevr** [comment]
Most of the vastly mispriced items I've seen have to do with bases; elder, shaper bases that aren't really favored in the economy at the moment.

E: I'll get some real examples for you soon and update this post.

**Comment by kevr** [comment]
Alright, well here's an example without a shaper/elder base anyway, a 6L chest with 100 life and 40 resist is being macro'd as 40+ exalted orbs. Nothing special really about the chest other than some T1s.

Here's an image of the item in-game: https://serving.photos.photobox.com/858499585d471eeff14fe3b316d2dc187cb512042c02f0d5f908d30817c5816d2c5336dd.jpg

Of course, the 40c is just a random sale amount I put up, it has nothing to do with the real price of it.

But yes, it looks like the majority of the issues have to do with bases - ilvl 85 shaper bases going for many exalts on the macro.

**Comment by Ethck** [comment]
Saving for later:
Rarity: Rare
Vengeance Curtain
Destiny Leather
--------
Quality: +20% (augmented)
Evasion Rating: 721 (augmented)
--------
Requirements:
Level: 59
Dex: 160
--------
Sockets: G-R-G-G-G-G 
--------
Item Level: 80
--------
+12 to Dexterity
+108 to maximum Life
+42% to Lightning Resistance
Reflects 44 Physical Damage to Melee Attackers
+30% to Cold Resistance (crafted)
--------
Note: ~price 40 chaos

**Comment by Ethck** [comment]
That exact item is only showing on average a 12c value for me... Can you post the output of the script when you price this item?

**Comment by Ethck** [comment]
Actually, it appears there are some other issues with the dev version of the script... Let me investigate.

**Comment by kevr** [comment]
Indeed, the values seem to have changed after restarting it. Now it's showing 40c for the item on my macro, but I think that was somehow tied to the price I set it to (40c) in the sale stash tab.

**Comment by kevr** [comment]
Is there a Discord server I could join to report some of these items to you over time? I would love to help out.

**Comment by kevr** [comment]
```
Loaded 5188 item mods.
If you wish to change the selected league you may do so in settings.cfg.
Valid league values are Metamorph, Hardcore Metamorph, Standard, Hardcore.
All values will be from the Metamorph league
[*] Watching clipboard (Ctrl+C to stop)...
[*] Found Rare item in clipboard: Vengeance Curtain Destiny Leather
[+] Found mod # to Dexterity: 12
[+] Found mod # to maximum Life: 108
[+] Found mod #% to Lightning Resistance: 42
[+] Found mod Reflects # Physical Damage to Melee Attackers: 44
[o] Combining the elemental resistance mods from the list into a pseudo-parameter
[+] Pseudo-mod +42% total Elemental Resistance (pseudo)
[o] Combining the maximum life mods from the list into a pseudo-parameter
[+] Pseudo-mod +108 to maximum Life (pseudo)
[-] Removing the # to Dexterity mod from the list due to no results found.
[-] Removing the Reflects # Physical Damage to Melee Attackers mod from the list due to no results found.
[$] Price: 1 x 20 chaos, 1 x 25 chaos, 1 x 30 chaos, 1 x 35 chaos, 2 x 40 chaos, 1 x 45 chaos, 1 x 50 chaos, 1 x 65 chaos, 1 x 66 chaos
```

Here's the new output after restarting it (and moving the item out of my stash tab)

**Comment by Ethck** [comment]
That seems fairly reasonable for that item. How long did you have the program running before hand? Also, does having it in your stash change the price?

**Comment by kevr** [comment]
It does seem reasonable after the restart. When I made this post before restarting the macro, it was running for a bit over a day. I've got some more shaper examples for you coming in shortly.

**Comment by kevr** [comment]
Here's a shaper base ilvl 85 vaal regalia. The macro window that pops up shows me 41+ ex.

```
[*] Found Rare item in clipboard: Gale Ward Vaal Regalia
[+] Found mod # to maximum Energy Shield: 36
[+] Found mod # to maximum Mana: 23
[+] Found mod #% to Cold Resistance: 10
[+] Found mod Recover #% of Mana on Kill: 4
[o] Combining the elemental resistance mods from the list into a pseudo-parameter
[+] Pseudo-mod +10% total Elemental Resistance (pseudo)
[-] Removing the # to maximum Energy Shield mod from the list due to no results found.
[$] Price: 1 x 2 chaos, 1 x 3 chaos, 2 x 5 chaos, 1 x 10 chaos, 1 x 15 chaos, 1 x 20 chaos, 1 x 50 chaos, 1 x 85 chaos, 1 x 1 exa
```

**Comment by Ethck** [comment]
https://discord.gg/mfKT7E

**Comment by Ethck** [comment]
Possible fix with carriage return commit. 558f6804f3a3356aa70e21495245ee7e3cf5cb4f
