### ISSUE TITLE
Cortex Map Lookup Error

### ISSUE THREAD

**Issue by Kholds** [Ethck/Path-of-Accounting#87]
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Failed to parse response from POE API. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Macro failed to lookup item from POE trade API. Here is the item in question.
====== ITEM DATA=====
Rarity: Unique
Cortex
Relic Chambers Map
--------
Map Tier: 3
Item Quantity: +108% (augmented)
Monster Pack Size: +25% (augmented)
Quality: +8% (augmented)
--------
Item Level: 84
--------
100% increased Experience gain
Monster Level: 83
Map has 3 additional random Modifiers
Map has 2 additional Synthesis Global Modifiers
--------
Though my life is gone, my purpose is not.
My will remains, emboldened and empowered
by the righteousness of my cause.
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================

**Comment by Ethck** [comment]
Looking into a fix now.

**Comment by Ethck** [comment]
Fixed in dev branch. Will make a new release by the end of the week.
