### ISSUE TITLE
Vaal Purity of * error

### ISSUE THREAD

**Issue by kevinrobbins** [Ethck/Path-of-Accounting#88]
[*] Found Gem item in clipboard: Purity of Ice Vaal Purity of Ice
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS BELOW ==================
[!] Failed to parse response from POE API. If this error occurs again please open an issue at https://github.com/Ethck/Path-of-Accounting/issues with the info below
================== START ISSUE DATA ==================
Title:
Failed to query item from trade API.
Body:
Macro failed to lookup item from POE trade API. Here is the item in question.
====== ITEM DATA=====
Rarity: Gem
Purity of Ice
--------
Aura, Vaal, Spell, AoE, Duration, Cold
Level: 1
Mana Reserved: 35%
Cooldown Time: 1.20 sec
Cast Time: Instant
Quality: +5% (augmented)
Experience: 1/118,383
--------
Requirements:
Level: 24
Dex: 37
Int: 25
--------
Casts an aura that grants cold resistance to you and your allies.
--------
10% increased Area of Effect
You and nearby allies gain 22% additional Cold Resistance
--------
Vaal Impurity of Ice
--------
Cooldown Time: 0.50 sec
Souls Per Use: 50
Can Store 1 Use
Soul Gain Prevention: 8 sec
Cast Time: Instant
--------
Casts an aura that reduces cold damage taken and provides freeze and chill immunity to you and nearby allies, and makes hits against nearby enemies ignore their cold resistance.
--------
Base duration is 3.00 seconds
Modifiers to Skill Effect Duration also apply to this Skill's Soul Gain Prevention
+14 to radius
10% increased Area of Effect
25% less Cold Damage taken
You and nearby allies are Immune to Chill
You and nearby allies are Immune to Freeze
Nearby Enemies' Cold Resistance is Ignored by Hits
--------
Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.
--------
Corrupted

================== END ISSUE DATA ==================
================== LOOKUP FAILED, PLEASE READ INSTRUCTIONS ABOVE ==================

**Comment by Ethck** [comment]
Thank you for the data. It turns out, when Purity of * gems are vaal gems they become Impurity gems... I did not know this. I'll have a fix out soon.
