### ISSUE TITLE
Broke with

### ISSUE THREAD

**Issue by Heckner** [Ethck/Path-of-Accounting#9]
Rarity: Unique
Rek'tar, the Breaker's Liver
--------
Uses: Leap Slam
--------
Item Level: 69
--------
Drops additional Currency Items
--------
Combine this with four other different samples in Tane's Laboratory.
//

Rarity: Normal
Sacrifice at Dawn
--------
Only those who aspire can dare to hope.
--------
Can be used in a personal Map Device.
//

**Comment by Ethck** [comment]
Refer to #18
