### ISSUE TITLE
[DEV] wikiLookup Function fails on Magic Item

### ISSUE THREAD

**Issue by Ethck** [Ethck/Path-of-Accounting#98]
Rarity: Magic
Rotund Sun Plate of the Lizard
--------
Armour: 451
--------
Requirements:
Level: 45
Str: 124
--------
Sockets: G-G-R-R-R 
--------
Item Level: 61
--------
+64 to maximum Life
Regenerate 2.5 Life per second

**Comment by Ethck** [comment]
This is because `parse_item_info()` does not understand how to turn "Rotund Sun Plate of the Lizard" into a valid item type.

**Comment by Jlance999** [comment]
https://github.com/Ethck/Path-of-Accounting/pull/105

Stops this issue from crashing the program, but does not add support for looking up magic items. Prophecies, Divination Cards, Rare Items, Unique Items, Skill Gems, and Normal items have all been tested and work.
